name: Update Equicord Plugins

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

jobs:
    run-script:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Run Python script
              run: python scripts/plugins.py

            - name: Check for changes
              run: git diff --exit-code || echo "Changes detected"

            - name: Commit changes
              if: success()
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git add .
                  git commit -m " Update Equicord Plugins" || echo "No changes to commit"

            - name: Push changes
              if: success()
              uses: ad-m/github-push-action@v0.8.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: main
